version: '3'
services:
 
  #PHP-APACHE
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php-apache-vitafy
    restart: always
    ports:
      - "8080:80"
    tty: true
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker-volumes/apache_config:/etc/apache2/sites-available
    networks:
      - app-network

  #MySQL
  db:
    image: mysql:8.4
    container_name: db-mysql-vitafy
    restart: always
    ports:
      - "3307:3306"
    tty: true
    environment:
      MYSQL_DATABASE: app_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user_db
      MYSQL_PASSWORD: pass_db
    volumes:
        - ./docker-volumes/mysql_data:/var/lib/mysql
    networks:
      - app-network
 
#Redes
networks:
  app-network:
    driver: bridge